language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 5.3
    - php: 5.4
    - php: 7.0

before_script:
  # Install Nette Tester
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/tester tests -s
  - vendor/bin/phpcs --standard=standards.xml --extensions=php --encoding=utf-8 -sp src
